name: Deploy Branch

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      AWS_PRE_MERGE_ROLE_ARN: { required: true }
      AWS_PRE_MERGE_S3_BUCKET_NAME: { required: true }
      PREMERGE_PARAMETER_PREFIX_STACK_NAME: { required: true }
    outputs:
      stack-name:
        description: The deployed stack name
        value: ${{ jobs.deploy.outputs.stack-name }}
      aws-region:
        description: The region in which the stack was deployed
        value: ${{ jobs.deploy.outputs.aws-region }}

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build SAM app
    runs-on: ubuntu-latest
    permissions: {}
    concurrency:
      group: build-development-${{ github.head_ref || github.ref_name }}
    outputs:
      sha_short: ${{ steps.vars.outputs.sha_short }}
      repo_base_dir : ${{ steps.vars.outputs.repo_base_dir }}
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: zulu

      - uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2
        with:
          gradle-version: wrapper
          cache-overwrite-existing: true

      - name: Check out repository code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Get output variables
        id: vars
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "repo_base_dir=$(pwd)" >> $GITHUB_OUTPUT

      - name: Build SAM application
        uses: govuk-one-login/github-actions/sam/build-application@a531d6d1728c39ebc292abf2cf1738d4e43ebd44
        id: build
        with:
          sam-version: "1.134.0"
          base-dir: ${{ steps.vars.outputs.repo_base_dir }}
          template: infrastructure/lambda/template.yaml
          cache-name: ipv-cri-dl-api-${{ steps.vars.outputs.sha_short }}
          pull-repository: true

  deploy:
    name: Deploy stack
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: build
    concurrency:
      group: deploy-development-${{ github.head_ref || github.ref_name }}
    environment:
      name: development
      url: ${{ steps.deploy.outputs.stack-url }}
    outputs:
      aws-region: ${{ steps.deploy.outputs.aws-region }}
      stack-name: ${{ steps.deploy.outputs.stack-name }}
    steps:
      - name: Deploy stack
        uses: govuk-one-login/github-actions/sam/deploy-stack@a531d6d1728c39ebc292abf2cf1738d4e43ebd44
        id: deploy
        with:
          sam-deployment-bucket: ${{ secrets.AWS_PRE_MERGE_S3_BUCKET_NAME }}
          aws-role-arn: ${{ secrets.AWS_PRE_MERGE_ROLE_ARN }}
          stack-name: preview-${{ needs.build.outputs.sha_short}}
          cache-name: ipv-cri-dl-api-${{ needs.build.outputs.sha_short}}
          s3-prefix: preview
          pull-repository: true
          delete-failed-stack: true
          tags: |
            cri:component=ipv-cri-dl-api
            cri:stack-type=preview
            cri:application=Lime
            cri:deployment-source=github-actions
          parameters: |
            DeploymentType=pre-merge-integration
            ParameterPrefix=${{ secrets.PREMERGE_PARAMETER_PREFIX_STACK_NAME }}
            Environment=dev
            CommonStackName=driving-permit-common-cri-api-local
