name: Deploy to dev
on:
  push:
    branches:
      - main
  workflow_dispatch: # deploy manually

jobs:
  deploy:
    name: Deploy to dev
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      AWS_REGION: eu-west-2
      STACK_NAME: driving-permit-cri-pipeline
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: zulu

      - uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582
        with:
          gradle-version: wrapper
          cache-overwrite-existing: true

      - name: Setup SAM
        uses: aws-actions/setup-sam@f664fad9e12492edfc187a31f575537dfbb0ff63
        with:
          use-installer: true
          version: "1.134.0"

      - name: Assume temporary AWS role
        uses: aws-actions/configure-aws-credentials@00943011d9042930efac3dcd3a170e4273319bc8
        with:
          role-to-assume: ${{ secrets.AWS_DL_DEV_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@33f92af657bba1882ab79d8621debd2f6769a0c9

      - name: Install Cosign
        uses: sigstore/cosign-installer@d7543c93d881b35a8faa02e8e3605f69b7a1ce62
        with:
          cosign-release: 'v2.5.2'

      - name: Build, push traffic test image to ECR
        uses: govuk-one-login/devplatform-upload-action-ecr@224346cd422f5bdfb6b68d0f8e189e55354b2804 # pin@1.4.0
        with:
          artifact-bucket-name: ""
          container-sign-kms-key-arn: ${{ secrets.CONTAINER_SIGN_KMS_KEY_TEST }}
          role-to-assume-arn: ${{ secrets.AWS_DL_DEV_ROLE_ARN }}
          ecr-repo-name: ${{ secrets.ECR_REPOSITORY_TRAFFIC_DEV }}
          dockerfile: Dockerfile-traffictest
          working-directory: acceptance-tests
          build-and-push-image-only: true
          push-latest-tag: true

      - name: reset to working directory
        run: cd ${GITHUB_WORKSPACE}

      - name: SAM Validate
        run: sam validate --region ${{ env.AWS_REGION }} -t infrastructure/lambda/template.yaml --lint

      - name: SAM build
        run: |
          mkdir out
          chmod a+x gradlew
          sam build -s "${GITHUB_WORKSPACE}" -t infrastructure/lambda/template.yaml -b out

      - name: Deploy SAM app
        uses: govuk-one-login/devplatform-upload-action@dc8158079d3976d613515180e543930cdbe73f5f
        with:
          artifact-bucket-name: "${{ secrets.DEV_ARTIFACT_SOURCE_BUCKET_NAME }}"
          signing-profile-name: "${{ secrets.DEV_SIGNING_PROFILE_NAME }}"
          working-directory: ./out
