name: Smoke Test against Build

on:
  schedule:
    # Every weekday at 5:00AM, 9:00AM, 12:00PM and 14:00PM
    - cron: "0 5,9,12,14 * * 1-5"
  push:

concurrency:
  group: smoke-test-build
  cancel-in-progress: false

jobs:
  smoke:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
          submodules: true
      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: zulu
          cache: gradle
      - uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2
        with:
          gradle-version: wrapper
          cache-overwrite-existing: true
      - name: Build Cache
        uses: actions/cache@v4
        with:
          path: |
            .gradle/
            */build/
            */**/build/
            !*/build/reports
            !*/build/jacoco
          key: ${{ runner.os }}-build-${{ github.sha }}

      - name: Run Smoke test against build environment
        env:
          BROWSER: chrome-headless
          ENVIRONMENT: ${{ secrets.TEST_ENVIRONMENT }}
          coreStubUrl: ${{ secrets.CORE_STUB_URL }}
          coreStubUsername: ${{ secrets.CORE_STUB_USERNAME }}
          coreStubPassword: ${{ secrets.CORE_STUB_PASSWORD }}
          orchestratorStubUrl: ${{ secrets.ORCHESTRATOR_STUB_URL }}
        run: cd acceptance-tests && ./gradlew smokeTestBuild

      - name: Get test results history
        uses: actions/checkout@v5
        if: always()
        continue-on-error: true
        with:
          ref: LIME-DL-Cucumber-gh-pages
          path: LIME-DL-Cucumber-gh-pages

      - name: Cucumber HTML Report action
        uses: PavanMudigonda/html-reporter-github-pages@54c76f16127af1800cbc0187ac458a9e347addd4
        id: test-report
        if: always()
        with:
          test_results: acceptance-tests/target/cucumber-report
          gh_pages: LIME-DL-Cucumber-gh-pages
          results_history: acceptance-tests/results-history

      - name: Publish Github Pages
        if: always() && ${{ github.actor != 'dependabot[bot]' }}
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: LIME-DL-Cucumber-gh-pages
          publish_dir: acceptance-tests/results-history
          keep_files: true
